### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Not Found

### ISSUE THREAD

**Issue by uditjn** [sguilly/loopback-nodejs-client#6]
node: v8.11.4
npm: 6.9.0

Trace:
(node:49595) UnhandledPromiseRejectionWarning: Error: Not Found
    at handleErrors (.../node_modules/loopback-nodejs-client/src/LoopbackClient.js:13:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:49595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:49595) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any idea on how to fix this?

**Comment by uditjn** [comment]
timeout option fixed it.
